### ISSUE TITLE
Crash trying to send embed

### ISSUE THREAD

**Issue by innocentDE** [innocentDE/osu-flex#4]
```java
Exception in thread "main" net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_SEND

    at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:64)

    at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildChannelMixin.checkPermission(GuildChannelMixin.java:56)

    at net.dv8tion.jda.internal.entities.channel.mixin.middleman.GuildMessageChannelMixin.checkCanSendMessage(GuildMessageChannelMixin.java:129)

    at net.dv8tion.jda.internal.entities.channel.mixin.middleman.MessageChannelMixin.sendMessageEmbeds(MessageChannelMixin.java:143)

    at com.flex.osu.Flex.sendEmbedIfInBest(Flex.java:94)

    at com.flex.osu.Flex.start(Flex.java:72)

    at com.flex.Main.main(Main.java:33)
```

**Comment by innocentDE** [comment]
After ONE google search, it turns out it's because the bot does not have sufficient permissions for a channel after being invited with the correct permissions, becuase server roles overwrite it somehow
